// <auto-generated />
using System;
using MathIBook.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MathIBook.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260715132516_AlignDatabaseWithSpecificationV11")]
    partial class AlignDatabaseWithSpecificationV11
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MathIBook.Domain.Entities.Badge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConditionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ConditionValue")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IconUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("RewardCoins")
                        .HasColumnType("integer");

                    b.Property<string>("RuleMatchMode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsActive", "IsDeleted");

                    b.ToTable("Badges", t =>
                        {
                            t.HasCheckConstraint("CK_Badges_RewardCoins", "\"RewardCoins\" >= 0");

                            t.HasCheckConstraint("CK_Badges_RuleMatchMode", "\"RuleMatchMode\" IN ('ALL', 'ANY')");
                        });
                });

            modelBuilder.Entity("MathIBook.Domain.Entities.BadgeRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BadgeId")
                        .HasColumnType("uuid");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<string>("Parameters")
                        .HasColumnType("jsonb");

                    b.Property<string>("RuleType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("TargetChapterId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TargetQuizId")
                        .HasColumnType("uuid");

                    b.Property<int?>("ThresholdValue")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TargetChapterId");

                    b.HasIndex("TargetQuizId");

                    b.HasIndex("BadgeId", "OrderIndex")
                        .IsUnique();

                    b.ToTable("BadgeRules", t =>
                        {
                            t.HasCheckConstraint("CK_BadgeRules_Threshold", "\"ThresholdValue\" IS NULL OR \"ThresholdValue\" >= 0");
                        });
                });

            modelBuilder.Entity("MathIBook.Domain.Entities.Chapter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CurriculumTopicId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CurriculumTopicId");

                    b.HasIndex("OrderIndex");

                    b.HasIndex("IsPublished", "IsDeleted", "OrderIndex");

                    b.ToTable("Chapters");
                });

            modelBuilder.Entity("MathIBook.Domain.Entities.ChapterProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("BestScore10")
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)");

                    b.Property<Guid>("ChapterId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ClientUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FirstPassedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("QuizUnlockedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ChapterId");

                    b.HasIndex("UserId", "ChapterId")
                        .IsUnique();

                    b.ToTable("ChapterProgresses", t =>
                        {
                            t.HasCheckConstraint("CK_ChapterProgresses_BestScore10", "\"BestScore10\" BETWEEN 0 AND 10");
                        });
                });

            modelBuilder.Entity("MathIBook.Domain.Entities.CoinTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<int>("BalanceAfter")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ClientAttemptId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<Guid?>("RewardPolicyId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SourceId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasFilter("\"IdempotencyKey\" IS NOT NULL");

                    b.HasIndex("RewardPolicyId");

                    b.HasIndex("UserId", "CreatedAt");

                    b.ToTable("CoinTransactions", t =>
                        {
                            t.HasCheckConstraint("CK_CoinTransactions_Amount", "\"Amount\" >= 0");

                            t.HasCheckConstraint("CK_CoinTransactions_BalanceAfter", "\"BalanceAfter\" >= 0");
                        });
                });

            modelBuilder.Entity("MathIBook.Domain.Entities.ContentAuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("AdminUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("AfterData")
                        .HasColumnType("jsonb");

                    b.Property<string>("BeforeData")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("AdminUserId", "CreatedAt");

                    b.HasIndex("EntityType", "EntityId", "CreatedAt");

                    b.ToTable("ContentAuditLogs");
                });

            modelBuilder.Entity("MathIBook.Domain.Entities.CurriculumTopic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Grade")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<int>("Strand")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Strand", "OrderIndex");

                    b.ToTable("CurriculumTopics", t =>
                        {
                            t.HasCheckConstraint("CK_CurriculumTopics_Grade", "\"Grade\" = 8");
                        });
                });

            modelBuilder.Entity("MathIBook.Domain.Entities.Lesson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChapterId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContentBody")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ContentVersion")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CurriculumTopicId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SimulationType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CurriculumTopicId");

                    b.HasIndex("ChapterId", "OrderIndex");

                    b.HasIndex("IsPublished", "IsDeleted");

                    b.ToTable("Lessons", t =>
                        {
                            t.HasCheckConstraint("CK_Lessons_ContentVersion", "\"ContentVersion\" > 0");
                        });
                });

            modelBuilder.Entity("MathIBook.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Link")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("RelatedEntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "IsRead", "CreatedAt");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("MathIBook.Domain.Entities.Progress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BestScore")
                        .HasColumnType("integer");

                    b.Property<decimal>("BestScore10")
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)");

                    b.Property<DateTime>("ClientUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("ContentViewed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastViewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.HasIndex("UserId", "LessonId")
                        .IsUnique();

                    b.ToTable("Progresses", t =>
                        {
                            t.HasCheckConstraint("CK_Progresses_BestScore10", "\"BestScore10\" BETWEEN 0 AND 10");
                        });
                });

            modelBuilder.Entity("MathIBook.Domain.Entities.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ChapterId")
                        .HasColumnType("uuid");

                    b.Property<int>("CorrectOption")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Explanation")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("LessonId")
                        .HasColumnType("uuid");

                    b.Property<string>("Options")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ChapterId", "OrderIndex");

                    b.HasIndex("LessonId", "OrderIndex");

                    b.ToTable("Questions", t =>
                        {
                            t.HasCheckConstraint("CK_Questions_CorrectOption", "\"CorrectOption\" BETWEEN 0 AND 3");

                            t.HasCheckConstraint("CK_Questions_SingleScope", "(\"LessonId\" IS NOT NULL AND \"ChapterId\" IS NULL) OR (\"LessonId\" IS NULL AND \"ChapterId\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("MathIBook.Domain.Entities.Quiz", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ChapterId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("integer");

                    b.Property<int>("FirstPassCoins")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("LessonId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("PassScore")
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("QuizType")
                        .HasColumnType("integer");

                    b.Property<Guid?>("RewardPolicyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ChapterId")
                        .IsUnique()
                        .HasFilter("\"ChapterId\" IS NOT NULL AND \"IsDeleted\" = FALSE");

                    b.HasIndex("LessonId")
                        .IsUnique()
                        .HasFilter("\"LessonId\" IS NOT NULL AND \"IsDeleted\" = FALSE");

                    b.HasIndex("RewardPolicyId");

                    b.HasIndex("QuizType", "IsPublished", "IsDeleted");

                    b.ToTable("Quizzes", t =>
                        {
                            t.HasCheckConstraint("CK_Quizzes_Duration", "\"DurationSeconds\" > 0");

                            t.HasCheckConstraint("CK_Quizzes_FirstPassCoins", "\"FirstPassCoins\" >= 0");

                            t.HasCheckConstraint("CK_Quizzes_PassScore", "\"PassScore\" BETWEEN 0 AND 10");

                            t.HasCheckConstraint("CK_Quizzes_Target", "(\"QuizType\" = 1 AND \"LessonId\" IS NOT NULL AND \"ChapterId\" IS NULL) OR (\"QuizType\" = 2 AND \"ChapterId\" IS NOT NULL AND \"LessonId\" IS NULL)");
                        });
                });

            modelBuilder.Entity("MathIBook.Domain.Entities.QuizAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ClientAttemptId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ClientCreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CoinsEarned")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("integer");

                    b.Property<bool>("IsPassed")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("LessonId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("QuizId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("RewardProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<decimal>("Score10")
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)");

                    b.Property<DateTime?>("SyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TotalQuestions")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ClientAttemptId")
                        .IsUnique()
                        .HasFilter("\"ClientAttemptId\" IS NOT NULL");

                    b.HasIndex("LessonId");

                    b.HasIndex("UserId", "CreatedAt");

                    b.HasIndex("QuizId", "UserId", "CreatedAt");

                    b.ToTable("QuizAttempts", t =>
                        {
                            t.HasCheckConstraint("CK_QuizAttempts_CoinsEarned", "\"CoinsEarned\" >= 0");

                            t.HasCheckConstraint("CK_QuizAttempts_Score10", "\"Score10\" BETWEEN 0 AND 10");

                            t.HasCheckConstraint("CK_QuizAttempts_Target", "\"QuizId\" IS NOT NULL OR \"LessonId\" IS NOT NULL");
                        });
                });

            modelBuilder.Entity("MathIBook.Domain.Entities.QuizAttemptAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AttemptId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<int>("SelectedOption")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("AttemptId", "QuestionId")
                        .IsUnique();

                    b.ToTable("QuizAttemptAnswers", t =>
                        {
                            t.HasCheckConstraint("CK_QuizAttemptAnswers_SelectedOption", "\"SelectedOption\" BETWEEN -1 AND 3");
                        });
                });

            modelBuilder.Entity("MathIBook.Domain.Entities.QuizQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("QuizId")
                        .HasColumnType("uuid");

                    b.Property<int>("Weight")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("QuizId", "OrderIndex")
                        .IsUnique();

                    b.HasIndex("QuizId", "QuestionId")
                        .IsUnique();

                    b.ToTable("QuizQuestions", t =>
                        {
                            t.HasCheckConstraint("CK_QuizQuestions_Weight", "\"Weight\" > 0");
                        });
                });

            modelBuilder.Entity("MathIBook.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("MathIBook.Domain.Entities.RewardPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ChapterCompletionBonusCoins")
                        .HasColumnType("integer");

                    b.Property<int>("CoinsPerCorrectAnswer")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DailyCoinLimit")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FirstPassBonusCoins")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("PerfectScoreBonusCoins")
                        .HasColumnType("integer");

                    b.Property<int>("QuizType")
                        .HasColumnType("integer");

                    b.Property<int>("RetryRewardPercent")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("QuizType", "IsActive", "EffectiveFrom");

                    b.ToTable("RewardPolicies", t =>
                        {
                            t.HasCheckConstraint("CK_RewardPolicies_EffectiveRange", "\"EffectiveTo\" IS NULL OR \"EffectiveTo\" > \"EffectiveFrom\"");

                            t.HasCheckConstraint("CK_RewardPolicies_NonNegative", "\"CoinsPerCorrectAnswer\" >= 0 AND \"FirstPassBonusCoins\" >= 0 AND \"PerfectScoreBonusCoins\" >= 0 AND \"ChapterCompletionBonusCoins\" >= 0 AND (\"DailyCoinLimit\" IS NULL OR \"DailyCoinLimit\" >= 0)");

                            t.HasCheckConstraint("CK_RewardPolicies_RetryPercent", "\"RetryRewardPercent\" BETWEEN 0 AND 100");
                        });
                });

            modelBuilder.Entity("MathIBook.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Coins")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CoinsUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Role", "IsActive", "Coins");

                    b.ToTable("Users", t =>
                        {
                            t.HasCheckConstraint("CK_Users_Coins", "\"Coins\" >= 0");

                            t.HasCheckConstraint("CK_Users_Role", "\"Role\" IN ('Student', 'Admin')");
                        });
                });

            modelBuilder.Entity("MathIBook.Domain.Entities.UserBadge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BadgeId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BadgeRuleId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EarnedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("SourceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BadgeId");

                    b.HasIndex("BadgeRuleId");

                    b.HasIndex("UserId", "BadgeId")
                        .IsUnique();

                    b.HasIndex("UserId", "EarnedAt");

                    b.ToTable("UserBadges");
                });

            modelBuilder.Entity("MathIBook.Domain.Entities.BadgeRule", b =>
                {
                    b.HasOne("MathIBook.Domain.Entities.Badge", "Badge")
                        .WithMany("Rules")
                        .HasForeignKey("BadgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MathIBook.Domain.Entities.Chapter", "TargetChapter")
                        .WithMany("BadgeRules")
                        .HasForeignKey("TargetChapterId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MathIBook.Domain.Entities.Quiz", "TargetQuiz")
                        .WithMany("BadgeRules")
                        .HasForeignKey("TargetQuizId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Badge");

                    b.Navigation("TargetChapter");

                    b.Navigation("TargetQuiz");
                });

            modelBuilder.Entity("MathIBook.Domain.Entities.Chapter", b =>
                {
                    b.HasOne("MathIBook.Domain.Entities.CurriculumTopic", "CurriculumTopic")
                        .WithMany("Chapters")
                        .HasForeignKey("CurriculumTopicId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CurriculumTopic");
                });

            modelBuilder.Entity("MathIBook.Domain.Entities.ChapterProgress", b =>
                {
                    b.HasOne("MathIBook.Domain.Entities.Chapter", "Chapter")
                        .WithMany("Progresses")
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MathIBook.Domain.Entities.User", "User")
                        .WithMany("ChapterProgresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chapter");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MathIBook.Domain.Entities.CoinTransaction", b =>
                {
                    b.HasOne("MathIBook.Domain.Entities.RewardPolicy", "RewardPolicy")
                        .WithMany("CoinTransactions")
                        .HasForeignKey("RewardPolicyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MathIBook.Domain.Entities.User", "User")
                        .WithMany("CoinTransactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RewardPolicy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MathIBook.Domain.Entities.ContentAuditLog", b =>
                {
                    b.HasOne("MathIBook.Domain.Entities.User", "AdminUser")
                        .WithMany("ContentAuditLogs")
                        .HasForeignKey("AdminUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AdminUser");
                });

            modelBuilder.Entity("MathIBook.Domain.Entities.Lesson", b =>
                {
                    b.HasOne("MathIBook.Domain.Entities.Chapter", "Chapter")
                        .WithMany("Lessons")
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MathIBook.Domain.Entities.CurriculumTopic", "CurriculumTopic")
                        .WithMany("Lessons")
                        .HasForeignKey("CurriculumTopicId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Chapter");

                    b.Navigation("CurriculumTopic");
                });

            modelBuilder.Entity("MathIBook.Domain.Entities.Notification", b =>
                {
                    b.HasOne("MathIBook.Domain.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MathIBook.Domain.Entities.Progress", b =>
                {
                    b.HasOne("MathIBook.Domain.Entities.Lesson", "Lesson")
                        .WithMany("Progresses")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MathIBook.Domain.Entities.User", "User")
                        .WithMany("Progresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MathIBook.Domain.Entities.Question", b =>
                {
                    b.HasOne("MathIBook.Domain.Entities.Chapter", "Chapter")
                        .WithMany("Questions")
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MathIBook.Domain.Entities.Lesson", "Lesson")
                        .WithMany("Questions")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Chapter");

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("MathIBook.Domain.Entities.Quiz", b =>
                {
                    b.HasOne("MathIBook.Domain.Entities.Chapter", "Chapter")
                        .WithMany("Quizzes")
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MathIBook.Domain.Entities.Lesson", "Lesson")
                        .WithMany("Quizzes")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MathIBook.Domain.Entities.RewardPolicy", "RewardPolicy")
                        .WithMany("Quizzes")
                        .HasForeignKey("RewardPolicyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Chapter");

                    b.Navigation("Lesson");

                    b.Navigation("RewardPolicy");
                });

            modelBuilder.Entity("MathIBook.Domain.Entities.QuizAttempt", b =>
                {
                    b.HasOne("MathIBook.Domain.Entities.Lesson", "Lesson")
                        .WithMany("QuizAttempts")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MathIBook.Domain.Entities.Quiz", "Quiz")
                        .WithMany("Attempts")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MathIBook.Domain.Entities.User", "User")
                        .WithMany("QuizAttempts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");

                    b.Navigation("Quiz");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MathIBook.Domain.Entities.QuizAttemptAnswer", b =>
                {
                    b.HasOne("MathIBook.Domain.Entities.QuizAttempt", "Attempt")
                        .WithMany("Answers")
                        .HasForeignKey("AttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MathIBook.Domain.Entities.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Attempt");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("MathIBook.Domain.Entities.QuizQuestion", b =>
                {
                    b.HasOne("MathIBook.Domain.Entities.Question", "Question")
                        .WithMany("QuizQuestions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MathIBook.Domain.Entities.Quiz", "Quiz")
                        .WithMany("QuizQuestions")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("MathIBook.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("MathIBook.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MathIBook.Domain.Entities.UserBadge", b =>
                {
                    b.HasOne("MathIBook.Domain.Entities.Badge", "Badge")
                        .WithMany("UserBadges")
                        .HasForeignKey("BadgeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MathIBook.Domain.Entities.BadgeRule", "BadgeRule")
                        .WithMany()
                        .HasForeignKey("BadgeRuleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MathIBook.Domain.Entities.User", "User")
                        .WithMany("UserBadges")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Badge");

                    b.Navigation("BadgeRule");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MathIBook.Domain.Entities.Badge", b =>
                {
                    b.Navigation("Rules");

                    b.Navigation("UserBadges");
                });

            modelBuilder.Entity("MathIBook.Domain.Entities.Chapter", b =>
                {
                    b.Navigation("BadgeRules");

                    b.Navigation("Lessons");

                    b.Navigation("Progresses");

                    b.Navigation("Questions");

                    b.Navigation("Quizzes");
                });

            modelBuilder.Entity("MathIBook.Domain.Entities.CurriculumTopic", b =>
                {
                    b.Navigation("Chapters");

                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("MathIBook.Domain.Entities.Lesson", b =>
                {
                    b.Navigation("Progresses");

                    b.Navigation("Questions");

                    b.Navigation("QuizAttempts");

                    b.Navigation("Quizzes");
                });

            modelBuilder.Entity("MathIBook.Domain.Entities.Question", b =>
                {
                    b.Navigation("QuizQuestions");
                });

            modelBuilder.Entity("MathIBook.Domain.Entities.Quiz", b =>
                {
                    b.Navigation("Attempts");

                    b.Navigation("BadgeRules");

                    b.Navigation("QuizQuestions");
                });

            modelBuilder.Entity("MathIBook.Domain.Entities.QuizAttempt", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("MathIBook.Domain.Entities.RewardPolicy", b =>
                {
                    b.Navigation("CoinTransactions");

                    b.Navigation("Quizzes");
                });

            modelBuilder.Entity("MathIBook.Domain.Entities.User", b =>
                {
                    b.Navigation("ChapterProgresses");

                    b.Navigation("CoinTransactions");

                    b.Navigation("ContentAuditLogs");

                    b.Navigation("Notifications");

                    b.Navigation("Progresses");

                    b.Navigation("QuizAttempts");

                    b.Navigation("RefreshTokens");

                    b.Navigation("UserBadges");
                });
#pragma warning restore 612, 618
        }
    }
}
